const V2 = (()=>{
 const base=(()=>{const local=location.hostname==='localhost'||location.hostname==='127.0.0.1'||location.protocol==='file:';return localStorage.getItem('backendApiUrl')||(local?'http://localhost:5000/api':location.origin+'/api')})();
 const q=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
 const money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:0});
 async function get(path){const r=await fetch(base+path,{cache:'no-store'});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.message||'Request failed');return j.data}
 function card(label,value,sub){return `<div class="kpi"><div class="label">${q(label)}</div><div class="value">${value}</div><div class="sub">${q(sub||'')}</div></div>`}
 function link(page,params,text){return `<a href="${page}${params?'?'+params:''}" style="color:#0176d3;font-weight:700;text-decoration:none">${q(text)}</a>`}
 function render(data){const s=data.summary||{};document.getElementById('kpis').innerHTML=[
  card('Customers',s.customers,'Active master records'),card('Suppliers',s.suppliers,'Supplier master'),card('Open Enquiries',s.openEnquiries,money(s.pipeline)+' pipeline'),card('Open Quotations',s.openQuotations,money(s.quotationValue)+' quoted'),card('Weighted Pipeline',money(s.weightedPipeline),'Probability-adjusted'),card('Receivable',money(s.receivable),'Invoice balance'),card('Paid Value',money(s.paidValue),'Recorded collections'),card('Overdue Tasks',s.overdueTasks,'Follow-ups + activities'),card('Open Tickets',s.openTickets,'Service control')].join('');
 const ec=data.counts?.enquiryStatus||{};document.getElementById('pipeline').innerHTML=`<div style="display:flex;gap:8px;flex-wrap:wrap">${Object.entries(ec).map(([k,v])=>`<div class="module"><b>${q(k)}</b><span>${v} enquiries</span></div>`).join('')||'<div class="empty">No enquiry data yet.</div>'}</div><div style="margin-top:12px;font-size:12px"><b>Pipeline:</b> ${money(s.pipeline)} &nbsp; <b>Weighted:</b> ${money(s.weightedPipeline)} &nbsp; <b>Win:</b> ${s.wonEnquiries||0} &nbsp; <b>Lost:</b> ${s.lostEnquiries||0}</div>`;
 const ens=data.recent?.enquiries||[];document.getElementById('enquiries').innerHTML=ens.length?`<table class="table"><thead><tr><th>Enquiry</th><th>Customer</th><th>Status</th><th>Value</th></tr></thead><tbody>${ens.map(e=>`<tr><td>${link('enquiry.html','enquiryNo='+encodeURIComponent(e.enquiryNo||e.id),e.enquiryNo||e.id)}</td><td>${q(e.customerName||'-')}</td><td><span class="pill">${q(e.status||'New')}</span></td><td>${money(e.estimatedValue)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No enquiries found.</div>';
 const qs=data.recent?.quotations||[];document.getElementById('quotes').innerHTML=qs.length?`<table class="table"><thead><tr><th>Quotation</th><th>Customer</th><th>Status</th><th>Value</th></tr></thead><tbody>${qs.map(x=>`<tr><td>${link('quotation.html','refNo='+encodeURIComponent(x.refNo||x.id),x.refNo||x.id)}</td><td>${q(x.custName||'-')}</td><td><span class="pill">${q(x.status||'Saved')}</span></td><td>${money(x.grandTotal||x.totalValue)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No quotations found.</div>';
 const acts=[...(data.recent?.activities||[]),...(data.recent?.followUps||[])].sort((a,b)=>new Date(a.dueDate||a.createdAt||0)-new Date(b.dueDate||b.createdAt||0).getTime()).slice(0,10);document.getElementById('tasks').innerHTML=acts.length?acts.map(a=>`<div style="padding:9px 0;border-bottom:1px solid #edf0f3"><b>${q(a.subject||a.outcome||a.activityType||'Activity')}</b><div style="font-size:10px;color:#667085">${q(a.dueDate||a.nextFollowUp||a.activityDate||'')} · ${q(a.status||'Open')} · ${q(a.priority||'Medium')}</div></div>`).join(''):'<div class="empty">No activities or follow-ups found.</div>';
 }
 async function search(term){if(!term.trim()){document.getElementById('results').style.display='none';return}try{const rows=await get('/crm/v2/search?q='+encodeURIComponent(term));const el=document.getElementById('results');el.innerHTML=rows.length?rows.map(x=>`<div class="result" data-type="${q(x.type)}" data-id="${q(x.id)}"><b>${q(x.type)}</b> · ${q(x.ref)}<div style="font-size:11px;color:#667085">${q(x.name)}</div></div>`).join(''):'<div class="result">No records found.</div>';el.style.display='block'}catch(e){console.warn(e)}}
 function bind(){const input=document.getElementById('globalSearch'),results=document.getElementById('results');let timer;input.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>search(input.value),220)});document.addEventListener('click',e=>{const r=e.target.closest('.result');if(r&&r.dataset.id){const type=r.dataset.type.toLowerCase();const page={customer:'customer.html',supplier:'supplier.html',enquiry:'enquiry.html',quotation:'quotation.html',invoice:'invoice.html'}[type];if(type==='customer'||type==='supplier')location.href=`business360.html?type=${type}&id=${encodeURIComponent(r.dataset.id)}`;else if(page)location.href=page+'?id='+encodeURIComponent(r.dataset.id);return}if(!e.target.closest('.search'))results.style.display='none'});document.getElementById('modules').innerHTML=[['Customers','customer.html','Master data'],['Suppliers','supplier.html','Master data'],['Enquiries','enquiry.html','Sales intake'],['Quotations','quotation.html','Commercial'],['Business 360°','business360.html','Intelligence'],['Follow-ups','follow_up.html','Activities'],['Customer Support','customer_support.html','Service'],['Purchase','purchase.html','Procurement'],['Invoices','invoice.html','Billing'],['Reports','report.html','Management']].map(x=>`<div class="module" onclick="location.href='${x[1]}'"><b>${x[0]}</b><span>${x[2]}</span></div>`).join('')}
 return {async init(){try{const d=await get('/crm/v2/overview');render(d);bind()}catch(e){document.getElementById('kpis').innerHTML='<div class="card" style="grid-column:1/-1;color:#b42318">Unable to load CRM V2 data: '+q(e.message)+'</div>';bind()}}}})();document.addEventListener('DOMContentLoaded',()=>V2.init());
