
const state = { customers: [], contacts: [], plants: [], activities: [], documents: [], followups: [], selected: null, tab: 'overview' };
const esc = s => String(s ?? '').replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]));
const id = (p) => p + '_' + Date.now() + '_' + Math.random().toString(36).slice(2, 7);
async function api(path, opts = {}) { const r = await fetch(API_BASE_URL + path, { headers: { 'Content-Type': 'application/json', ...(opts.headers || {}) }, ...opts }); const j = await r.json(); if (!r.ok || j.success === false) throw Error(j.message || 'Request failed'); return j.data ?? j }
async function loadAll() { try { [state.customers, state.contacts, state.plants, state.activities, state.documents, state.followups] = await Promise.all([api('/customers'), api('/crm-contacts'), api('/crm-plants'), api('/crm-activities'), api('/crm-documents'), api('/follow-ups')]); renderCustomers(); renderSelected(); document.getElementById('cCustomers').textContent = state.customers.length; document.getElementById('cContacts').textContent = state.contacts.length; document.getElementById('cPlants').textContent = state.plants.length; document.getElementById('cActivities').textContent = state.activities.length; document.getElementById('cFollowups').textContent = state.followups.filter(x => x.status === 'Pending' || !x.status).length; document.getElementById('cDocuments').textContent = state.documents.length } catch (e) { toast(e.message) } }
function renderCustomers() { const q = (document.getElementById('customerSearch').value || '').toLowerCase(); const list = state.customers.filter(c => [c.name, c.contact, c.email, c.gstin, c.district, c.state].join(' ').toLowerCase().includes(q)); document.getElementById('customerList').innerHTML = list.length ? list.map(c => `<div class="customer ${state.selected?.id === c.id ? 'sel' : ''}" onclick="selectCustomer('${esc(c.id)}')"><b>${esc(c.name)}</b><small>${esc(c.district || '')}${c.state ? ' • ' + esc(c.state) : ''}</small><br><small class="muted">${esc(c.contact || c.email || '')}</small></div>`).join('') : '<div class="empty">No customers found.</div>' }
function selectCustomer(cid) { state.selected = state.customers.find(c => c.id === cid) || null; renderCustomers(); renderSelected() }
function showTab(tab) { state.tab = tab; document.querySelectorAll('.section').forEach(x => x.classList.toggle('active', x.id === tab)); document.querySelectorAll('.tab').forEach(x => x.classList.toggle('active', x.dataset.tab === tab)); document.querySelectorAll('.side .nav').forEach(x => x.classList.remove('active')); const nav = [...document.querySelectorAll('.side .nav')].find(x => x.textContent.trim().toLowerCase().includes(tab === 'overview' ? 'customer 360' : tab)); if (nav) nav.classList.add('active'); renderSelected() }
function renderSelected() {
    const c = state.selected; if (!c) { document.getElementById('overview').innerHTML = '<div class="empty"><i class="fas fa-hand-pointer fa-2x"></i><br><br>Select a customer to open Customer 360°.</div>';['contacts', 'plants', 'activities', 'followups', 'documents'].forEach(x => document.getElementById(x).innerHTML = '<div class="empty">Select a customer first.</div>'); return } const cid = c.id; const contacts = state.contacts.filter(x => x.customerId === cid), plants = state.plants.filter(x => x.customerId === cid), acts = state.activities.filter(x => x.customerId === cid), docs = state.documents.filter(x => x.customerId === cid), fus = state.followups.filter(x => x.partyId === cid || (!x.partyId && x.party === c.name)); document.getElementById('overview').innerHTML = `<div class="toolbar"><button class="primary" onclick="openContact()"><i class="fas fa-user-plus"></i> Contact</button><button class="success" onclick="openPlant()"><i class="fas fa-industry"></i> Plant</button><button class="secondary" onclick="openActivity()"><i class="fas fa-plus"></i> Activity</button><button class="secondary" onclick="openFollowup()"><i class="fas fa-bell"></i> Follow-up</button><button class="secondary" onclick="openDocument()"><i class="fas fa-paperclip"></i> Document</button></div><h2 style="margin:5px 0">${esc(c.name)}</h2><p class="muted">${esc(c.address || '')}${c.district ? ', ' + esc(c.district) : ''}${c.state ? ', ' + esc(c.state) : ''} ${c.pin ? '- ' + esc(c.pin) : ''}</p><div class="grid2"><div class="card"><b>Customer Information</b><p>GSTIN: ${esc(c.gstin || '-')}<br>Phone: ${esc(c.contact || '-')}<br>Email: ${esc(c.email || '-')}</p></div><div class="card"><b>CRM Summary</b><p>Contacts: ${contacts.length}<br>Plants: ${plants.length}<br>Activities: ${acts.length}<br>Open Follow-ups: ${fus.filter(x => x.status === 'Pending' || !x.status).length}<br>Documents: ${docs.length}</p></div></div><h3>Recent Activity</h3>${acts.slice(0, 8).map(a => `<div class="timeline"><div class="event"><b>${esc(a.subject || a.activityType)}</b> <span class="badge">${esc(a.activityType)}</span><br><small>${esc(a.activityDate || '')} ${esc(a.activityTime || '')}</small><p style="margin:5px 0">${esc(a.details || a.outcome || '')}</p></div></div>`).join('') || '<div class="empty">No activity recorded.</div>'}`;
    renderContacts(contacts); renderPlants(plants); renderActivities(acts); renderFollowups(fus); renderDocuments(docs)
}
function renderContacts(rows) { document.getElementById('contacts').innerHTML = `<div class="toolbar"><button class="primary" onclick="openContact()">+ New Contact</button></div><div class="tablewrap"><table class="data"><thead><tr><th>Name</th><th>Designation</th><th>Department</th><th>Mobile</th><th>Email</th><th>Primary</th></tr></thead><tbody>${rows.map(x => `<tr><td>${esc(x.name)}</td><td>${esc(x.designation)}</td><td>${esc(x.department)}</td><td>${esc(x.mobile)}</td><td>${esc(x.email)}</td><td>${x.isPrimary ? 'Yes' : '-'}</td></tr>`).join('') || '<tr><td colspan="6" class="empty">No contacts.</td></tr>'}</tbody></table></div>` }
function renderPlants(rows) { document.getElementById('plants').innerHTML = `<div class="toolbar"><button class="primary" onclick="openPlant()">+ New Plant</button></div><div class="tablewrap"><table class="data"><thead><tr><th>Plant</th><th>Code</th><th>Location</th><th>Industry</th><th>Status</th></tr></thead><tbody>${rows.map(x => `<tr><td><b>${esc(x.plantName)}</b><br><small>${esc(x.unitDetails || '')}</small></td><td>${esc(x.plantCode)}</td><td>${esc([x.district, x.state].filter(Boolean).join(', '))}</td><td>${esc(x.industry)}</td><td>${esc(x.status)}</td></tr>`).join('') || '<tr><td colspan="5" class="empty">No plants.</td></tr>'}</tbody></table></div>` }
function renderActivities(rows) { document.getElementById('activities').innerHTML = `<div class="toolbar"><button class="primary" onclick="openActivity()">+ Log Activity</button></div><div class="tablewrap"><table class="data"><thead><tr><th>Date</th><th>Type</th><th>Subject</th><th>Details</th><th>Next Action</th></tr></thead><tbody>${rows.map(x => `<tr><td>${esc(x.activityDate)} ${esc(x.activityTime)}</td><td><span class="badge">${esc(x.activityType)}</span></td><td>${esc(x.subject)}</td><td>${esc(x.details || x.outcome)}</td><td>${esc(x.nextAction || '-')}<br>${esc(x.nextFollowUp || '')}</td></tr>`).join('') || '<tr><td colspan="5" class="empty">No activities.</td></tr>'}</tbody></table></div>` }
function renderFollowups(rows) { document.getElementById('followups').innerHTML = `<div class="toolbar"><button class="primary" onclick="openFollowup()">+ New Follow-up</button></div><div class="tablewrap"><table class="data"><thead><tr><th>Date</th><th>Time</th><th>Status</th><th>Notes</th><th>Next Action</th></tr></thead><tbody>${rows.map(x => `<tr><td>${esc(x.date)}</td><td>${esc(x.time)}</td><td>${esc(x.status || 'Pending')}</td><td>${esc(x.notes || x.remarks || '')}</td><td>${esc(x.nextAction || '-')}</td></tr>`).join('') || '<tr><td colspan="5" class="empty">No follow-ups.</td></tr>'}</tbody></table></div>` }
function renderDocuments(rows) { document.getElementById('documents').innerHTML = `<div class="toolbar"><button class="primary" onclick="openDocument()">+ Add Document</button></div><div class="tablewrap"><table class="data"><thead><tr><th>Document</th><th>Type</th><th>Date</th><th>Reference</th><th>Remarks</th></tr></thead><tbody>${rows.map(x => `<tr><td>${esc(x.documentName)}</td><td>${esc(x.documentType)}</td><td>${esc(x.documentDate)}</td><td>${esc(x.referenceNo)}</td><td>${esc(x.remarks)}</td></tr>`).join('') || '<tr><td colspan="5" class="empty">No documents.</td></tr>'}</tbody></table></div>` }
function form(title, body, save) { document.getElementById('modalBody').innerHTML = `<h2 style="margin-top:0">${title}</h2>${body}<div class="toolbar" style="justify-content:flex-end;margin-top:14px"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" onclick="${save}">Save</button></div>`; document.getElementById('modal').classList.add('open') }
function closeModal() { document.getElementById('modal').classList.remove('open') }
function field(id, label, val = '', type = 'text', extra = '') { return `<div class="field"><label>${label}</label><input id="${id}" type="${type}" value="${esc(val)}" ${extra}></div>` } function textarea(id, label, val = '') { return `<div class="field"><label>${label}</label><textarea id="${id}">${esc(val)}</textarea></div>` }
function openContact() { if (!state.selected) return toast('Select a customer first'); form('New Contact', `<div class="grid2">${field('n', 'Name *')}${field('d', 'Designation')}${field('dep', 'Department')}${field('mob', 'Mobile')}${field('alt', 'Alternate Mobile')}${field('em', 'Email', '', 'email')}${field('pref', 'Preferred Communication', 'Phone')}${field('primary', 'Primary Contact', '', 'checkbox')}</div>${textarea('remarks', 'Remarks')}`, 'saveContact()') }
async function saveContact() { const p = { id: id('contact'), customerId: state.selected.id, customerName: state.selected.name, name: v('n'), designation: v('d'), department: v('dep'), mobile: v('mob'), alternateMobile: v('alt'), email: v('em'), preferredCommunication: v('pref'), isPrimary: document.getElementById('primary').checked, remarks: v('remarks') }; await api('/crm-contacts', { method: 'POST', body: JSON.stringify(p) }); closeModal(); await loadAll(); toast('Contact saved') }
function openPlant() { if (!state.selected) return toast('Select a customer first'); form('New Plant', `<div class="grid2">${field('pn', 'Plant Name *')}${field('pc', 'Plant Code')}${field('dist', 'District')}${field('st', 'State')}${field('pin', 'PIN')}${field('ind', 'Industry', 'Thermal Power')}${field('status', 'Status', 'Active')}</div>${textarea('addr', 'Address')}${textarea('units', 'Unit / Equipment Details')}${textarea('prem', 'Remarks')}`, 'savePlant()') }
async function savePlant() { const p = { id: id('plant'), customerId: state.selected.id, customerName: state.selected.name, plantName: v('pn'), plantCode: v('pc'), district: v('dist'), state: v('st'), pin: v('pin'), industry: v('ind'), status: v('status'), address: v('addr'), unitDetails: v('units'), remarks: v('prem') }; await api('/crm-plants', { method: 'POST', body: JSON.stringify(p) }); closeModal(); await loadAll(); toast('Plant saved') }
function openActivity() { if (!state.selected) return toast('Select a customer first'); const today = new Date().toISOString().slice(0, 10); form('Log Activity', `<div class="grid2">${field('atype', 'Activity Type', 'Call')}${field('adate', 'Date', today, 'date')}${field('atime', 'Time', '', 'time')}${field('sub', 'Subject *')}${field('next', 'Next Action')}${field('nfu', 'Next Follow-up', '', 'date')}</div>${textarea('details', 'Discussion / Details')}${textarea('outcome', 'Outcome')}`, 'saveActivity()') }
async function saveActivity() { const p = { id: id('activity'), customerId: state.selected.id, customerName: state.selected.name, activityType: v('atype'), activityDate: v('adate'), activityTime: v('atime'), subject: v('sub'), details: v('details'), outcome: v('outcome'), nextAction: v('next'), nextFollowUp: v('nfu') }; await api('/crm-activities', { method: 'POST', body: JSON.stringify(p) }); closeModal(); await loadAll(); toast('Activity logged') }
function openFollowup() { if (!state.selected) return toast('Select a customer first'); const d = new Date().toISOString().slice(0, 10); form('New Follow-up', `<div class="grid2">${field('fud', 'Follow-up Date *', d, 'date')}${field('fut', 'Time', '', 'time')}${field('fust', 'Status', 'Pending')}${field('fucon', 'Contact')}${field('fupart', 'Party', state.selected.name)}</div>${textarea('fun', 'Notes / Purpose')}${textarea('funa', 'Next Action')}`, 'saveFollowup()') }
async function saveFollowup() { const p = { id: id('followup'), partyType: 'Customer', partyId: state.selected.id, party: state.selected.name, contact: v('fucon'), date: v('fud'), time: v('fut'), status: v('fust'), notes: v('fun'), nextAction: v('funa') }; await api('/follow-ups', { method: 'POST', body: JSON.stringify(p) }); closeModal(); await loadAll(); toast('Follow-up saved') }
function openDocument() { if (!state.selected) return toast('Select a customer first'); form('Add Document', `<div class="grid2">${field('dn', 'Document Name *')}${field('dt', 'Document Type', 'General')}${field('dd', 'Document Date', '', 'date')}${field('dr', 'Reference No.')}</div><div class="field"><label>File</label><input id="df" type="file"></div>${textarea('dm', 'Remarks')}`, 'saveDocument()') }
async function saveDocument() { const f = document.getElementById('df').files[0]; let data = ''; if (f) { data = await new Promise((res, rej) => { const r = new FileReader(); r.onload = () => res(r.result); r.onerror = rej; r.readAsDataURL(f) }) } const p = { id: id('document'), customerId: state.selected.id, customerName: state.selected.name, documentName: v('dn'), documentType: v('dt'), documentDate: v('dd'), referenceNo: v('dr'), fileName: f?.name || '', mimeType: f?.type || '', fileData: data, remarks: v('dm') }; await api('/crm-documents', { method: 'POST', body: JSON.stringify(p) }); closeModal(); await loadAll(); toast('Document saved') }
function v(x) { return document.getElementById(x)?.value || '' } function toast(m) { const t = document.getElementById('toast'); t.textContent = m; t.style.display = 'block'; setTimeout(() => t.style.display = 'none', 2500) }
loadAll();
